kind: Pod
apiVersion: v1

metadata:
  name: hello-k8s
  labels:
    app: hello-k8s

spec:
  containers:
    - name: app
      image: busybox
      command:
        - sh
        - -c
        - echo "Hello Kubernetes!" && sleep 300
