kind: Job
apiVersion: batch/v1

metadata:
  name: pi
  labels:
    app: pi

spec:
  backoffLimit: 4

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: app
          image: perl
          command:
            - perl
            - -Mbignum=bpi
            - -wle
            - print bpi(2000)
