kind: Deployment
apiVersion: apps/v1

metadata:
  name: scaling
  labels:
    app: scaling

spec:
  replicas: 1
  revisionHistoryLimit: 2

  strategy:
    rollingUpdate:
      maxUnavailable: 1

  selector:
    matchLabels:
      app: scaling

  template:
    metadata:
      labels:
        app: scaling

    spec:
      containers:
        - name: app
          image: codeurjc/hpa-example:v1
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
