kind: Service
apiVersion: v1

metadata:
  name: web-server
  labels:
    app: web-server

spec:
  type: NodePort

  selector:
    app: web-server

  ports:
    - name: http
      port: 80
      targetPort: http
